### ISSUE TITLE
Same old issues...

### ISSUE THREAD

**Issue by Boolyman** [TheXFactor117/Levels#110]
I feel like we are having to report the same 1.10 bugs over and over again... and then they are claimed to be fixed... but they arent.

We were supposed to have accurate Armor traits two updates ago... but they are still (mostly) the same weapon enchants... even the descriptions talk about effects happening when damage is done... not received.

The Soul Bound trait doesn't do anything... your items are still lost upon death.

Rarities still give inaccurate damage value indicators on the weapon when enchants are applied,

**Comment by TheXFactor117** [comment]
Everything should be fixed. Everything was tested too. Double check your version?

**Comment by ruyanve** [comment]
Wow, the tone... You seem to be annoyed!

Oh and nope, everything works.

You must have done something wrong again. Judging by your reports in other repos, I guess you have the wrong version, that seems like something you don't seem to understand. (remember the JEI issue where you had the wrong version? Or the BQM bug you reported where you had the wrong version? Maybe even the Bloodmagic issue where you tried to use a wrong method?)

Here, let me explain... There are different versions. 
Use the new one.

Oh and how about being more humble? Just a tad of respect for people like X who put in a lot of work to give us something to enjoy without charging for it.
Thank you!

**Comment by TheXFactor117** [comment]
I'm assuming everything is working correctly, @ruyanve ?

**Comment by Boolyman** [comment]
No, its not working... I simply didnt respond earlier because I found a mod that did similar things without the self entitled rants from the developers when someone voices displeasure in their work.  And you just made up a bunch of stuff about my other reports... Good try.  I can make up claims too.  Like that time you slapped a lady at the bus stop.  

You must be unclear on something... these bug reports help YOU.  They make YOUR product better.  I can (and have) just as easily gone and use Silent Gems or Tinkers Addons, to do the same thing your mod does... instead of coming here to report all the bugs.  So take a taste of your own medicine and stop whining that you dont get paid for this... your mods aint nothing without a pack to put it in.  You dont see pack devs whining about not getting paid.

**Comment by TheXFactor117** [comment]
First and foremost, I am the sole developer of this mod, and I have not "ranted" in displeasure to you or anyone. I appreciate all of these bug reports because they help the mod out. Since when have I expressed opposition to them?

I tested the new version, both in my dev environment and outside too, in a mod pack. It was working for me, and according to @ruyanve everything was fixed for him too. All I said to you was asking what version you were using (which, if you don't know, helps developers out a lot if that information is provided), but since that wasn't provided, I can't do anything. I don't know if you are saying that for an old version or for the new one, so how do you expect me to fix anything or verify if what you are reporting is actually a problem.

Also, when have I ever complained about getting "paid"? I don't get paid at all for this. Who would pay me anyways? I'm not doing this to get money or make a living, but rather to do something I enjoy. Furthermore, why didn't you just stick with those other mods if mine was buggy? You obviously like helping mods out with reporting bugs, yet at the same time, you really don't. You report a bug, and then proceed to yell and scream and whine that it supposedly isn't fixed (which it might be broken under certain circumstances, I just don't have that information to determine if it is), and then go on a rant about money for no reason at all. Even if it was directed at @ruyanve he has no affiliation with the development of this mod, so I don't understand why you are angry at him for something he isn't even doing.

Instead of being so angry and displeased, why don't you actually help contribute to a project with a good mind, and if that isn't something you want to do, then don't help at all. I don't appreciate you getting upset and angry over a bug in my mod which breaks a certain feature. That's a part of programming, and when a bunch of amateur developers make unprofessional mods just for fun, those kind of things happen A LOT. Look at every other mod there ever was. Big bugs in all of them (some fixed, some still there). Even look at Minecraft as a game. So I don't quite understand why a bug like this is causing you to get so frustrated.

**Comment by TheXFactor117** [comment]
![2017-04-01_22 44 30](https://cloud.githubusercontent.com/assets/6678711/24584027/dfdcf51c-172c-11e7-8e85-916be5e92371.png)

And this is from my perspective. Tested using r1.2.8 for 1.10.2.

**Comment by Boolyman** [comment]
"yell and scream and whine that it supposedly isn't fixed"

Read my first post... then read what you wrote.  If its yelling, screaming, and whining just to say "hey I feel like our issues arent getting addressed"... then no wonder we are having problems.    If you are referring to my 2nd post, that was in response that had little to do with my original purpose for reporting the bug, and was simply responding to a person who is so childish that they assumed my first post was anything but adult.   In the real world, we adults can approach each other and say "Hey, I dont think this is right, or fair.  Or... I feel like you are ignoring me."  And its not called yellingl, screaming, whnining, unhumble, or any of the other things I was called in this forum.

Now as for me responding to that other guy, you are right, I did not recognize that it was some random forum lurker who was overreacting to my original post, and I should have ignored them.  That is my fault.

**Comment by TheXFactor117** [comment]
And that is what I am referring to about the whining part, but since you have seemed to get over that, maybe we can actually address and fix the issue properly.

Were you using the most up to date version, and furthermore, which Minecraft are you using. I got a second report of it being broken still, but he is using 1.10.2. The issue could very well be just for one specific Minecraft version, or it could also be an issue outside of a development environment. As much information as you have would be helpful.

**Comment by Boolyman** [comment]
![2017-04-01_20 02 19](https://cloud.githubusercontent.com/assets/24765883/24584119/3d285b3c-1717-11e7-9e38-8d84b828725f.png)
![2017-04-01_20 03 50](https://cloud.githubusercontent.com/assets/24765883/24584118/3d2852fe-1717-11e7-8f06-caa43a361f7d.png)

**I am in the middle of some things right now, so I cant level up and show you the soul bound trait isnt working.  At this point... its not really my concern anymore.  

Minecrat 1.10.2
Levels 2-1.10.2-r1.2.8**

**Comment by TheXFactor117** [comment]
Ok I see what's wrong. I never took sharpness into account when determining damage, but I will fix that. The ability descriptions are also a very easy fix. But as far as that, all those other issues seem to be fixed that you mentioned earlier.

**Comment by Boolyman** [comment]
"All those other issues?"  I dont know what you are talking about.  I named exactly three issues, some of the traits being the same as weapons, the damage value being wrong when enchants are present, and the soul bound not working.   What are all these other issues I brought up? 

On a side note, the traits are written very vaguely, referencing damage in the same way as it is referenced on weapons. Makes it a bit confusing.  But thats not necessarily a bug, just a suggestion.

**Comment by TheXFactor117** [comment]
Your last issue commented on how armor abilities were actually weapon abilities, in which I fixed. Furthermore, I didn't fully understand the bonus damage issue when you first reported it and thought you were referencing how the damage isn't actually applied. So in that sense, I fixed the issues you first opened, however, there were just more still there.
